var_1: &cache_key san-dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

anchor_1: &job_defaults
  working_directory: ~/san
  docker:
    - image: circleci/node:8.11.2-browsers
      environment:
        CHROME_BIN: "/usr/bin/google-chrome"

version: 2
jobs:
  build:
    <<: *job_defaults
    branches:
      only:
        - master
        
    steps:
      - checkout

      - restore_cache:
          key: *cache_key

      - run:
          name: install-npm-wee
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: *cache_key

      - run:
          name: test
          command: npm run test
