sudo: false
language: node_js
os:
#  - windows
  - linux
node_js:
  - '8'
  - '10'
cache:
  directories:
    - node_modules
addons:
  chrome: beta
script:
  - npm run test:coverage
notifications:
  email:
    on_success: never
    on_failure: always