environment:
  matrix:
    - nodejs_version: "8.12"
    - nodejs_version: "10"
cache:
  - node_modules
install:
  - ps: >-
      try { Install-Product node $env:nodejs_version -ErrorAction Stop }
      catch { Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) }
  - choco install googlechrome --ignore-checksums
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
build: off
test_script:
  - ps: |
      node --version
      npm --version
  - npm run test
version: "{build}"